/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "r_brok.h"

bool_t
xdr_r_bent (XDR *xdrs, r_bent *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->host, MAX_HOSTNAME))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->svcn, MAX_SVCNNAME))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->proto, MAX_PROTO))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->prgnr))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->versnr))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_r_cid (XDR *xdrs, r_cid *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->cid, MAX_CIDLENGTH))
		 return FALSE;
	return TRUE;
}
