/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "r_brok.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
r_brok_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		r_bent brok_register_1_arg;
		char *brok_unregister_1_arg;
		char *brok_bind_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case BROK_REGISTER:
		_xdr_argument = (xdrproc_t) xdr_r_bent;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) brok_register_1_svc;
		break;

	case BROK_UNREGISTER:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) brok_unregister_1_svc;
		break;

	case BROK_BIND:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_r_bent;
		local = (char *(*)(char *, struct svc_req *)) brok_bind_1_svc;
		break;

	case BROK_GET_CID:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_r_cid;
		local = (char *(*)(char *, struct svc_req *)) brok_get_cid_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
rpcgen_main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (R_BROK, R_BROK_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, R_BROK, R_BROK_VERSION, r_brok_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (R_BROK, R_BROK_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, R_BROK, R_BROK_VERSION, r_brok_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (R_BROK, R_BROK_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
