/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "r_brok.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
brok_register_1(r_bent *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, BROK_REGISTER,
		(xdrproc_t) (xdrproc_t) xdr_r_bent, (caddr_t) argp,
		(xdrproc_t) (xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
brok_unregister_1(char **argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, BROK_UNREGISTER,
		(xdrproc_t) (xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) (xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

r_bent *
brok_bind_1(char **argp, CLIENT *clnt)
{
	static r_bent clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, BROK_BIND,
		(xdrproc_t) (xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) (xdrproc_t) xdr_r_bent, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

r_cid *
brok_get_cid_1(void *argp, CLIENT *clnt)
{
	static r_cid clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, BROK_GET_CID,
		(xdrproc_t) (xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) (xdrproc_t) xdr_r_cid, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
