/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "r_knto.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

rknt *
knto_new_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_NEW, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_init_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_INIT, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_clear_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_CLEAR, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_delete_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_DELETE, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_set_konto_nummer_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_SET_KONTO_NUMMER, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_set_blz_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_SET_BLZ, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_set_bankname_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_SET_BANKNAME, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_set_betrag_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_SET_BETRAG, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_set_kunde_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_SET_KUNDE, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_set_unassigned_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_SET_UNASSIGNED, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_get_kunde_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_GET_KUNDE, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_get_konto_nummer_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_GET_KONTO_NUMMER, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_get_blz_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_GET_BLZ, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_get_bankname_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_GET_BANKNAME, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_get_betrag_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_GET_BETRAG, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_einzahlen_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_EINZAHLEN, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_auszahlen_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_AUSZAHLEN, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_find_by_key_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_FIND_BY_KEY, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_find_by_kunde_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_FIND_BY_KUNDE, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_find_unassigned_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_FIND_UNASSIGNED, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_get_rid_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_GET_RID, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_register_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_REGISTER, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknt *
knto_unregister_1(rknt *argp, CLIENT *clnt)
{
	static rknt clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNTO_UNREGISTER, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknt, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

/*
short *
dbms_commit_1(char **argp, CLIENT *clnt)
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DBMS_COMMIT, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_wrapstring, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_short, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

short *
dbms_rollback_1(char **argp, CLIENT *clnt)
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DBMS_ROLLBACK, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_wrapstring, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_short, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

short *
dbms_data_server_changed_1(void *argp, CLIENT *clnt)
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DBMS_DATA_SERVER_CHANGED, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_void, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_short, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
*/
