/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "r_knto.h"
#include <stdio.h>
#include <stdlib.h>/* getenv, exit */
#include <rpc/pmap_clnt.h> /* for pmap_unset */
#include <string.h> /* strcmp */ 
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifdef __STDC__
#define SIG_PF void(*)(int)
#endif

static void
r_knto_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		rknt knto_new_1_arg;
		rknt knto_init_1_arg;
		rknt knto_clear_1_arg;
		rknt knto_delete_1_arg;
		rknt knto_set_konto_nummer_1_arg;
		rknt knto_set_blz_1_arg;
		rknt knto_set_bankname_1_arg;
		rknt knto_set_betrag_1_arg;
		rknt knto_set_kunde_1_arg;
		rknt knto_set_unassigned_1_arg;
		rknt knto_get_kunde_1_arg;
		rknt knto_get_konto_nummer_1_arg;
		rknt knto_get_blz_1_arg;
		rknt knto_get_bankname_1_arg;
		rknt knto_get_betrag_1_arg;
		rknt knto_einzahlen_1_arg;
		rknt knto_auszahlen_1_arg;
		rknt knto_find_by_key_1_arg;
		rknt knto_find_by_kunde_1_arg;
		rknt knto_find_unassigned_1_arg;
		rknt knto_get_rid_1_arg;
		rknt knto_register_1_arg;
		rknt knto_unregister_1_arg;
		char *dbms_commit_1_arg;
		char *dbms_rollback_1_arg;
	} argument;
	char *result;
	xdrproc_t xdr_argument, xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case KNTO_NEW:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_new_1_svc;
		break;

	case KNTO_INIT:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_init_1_svc;
		break;

	case KNTO_CLEAR:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_clear_1_svc;
		break;

	case KNTO_DELETE:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_delete_1_svc;
		break;

	case KNTO_SET_KONTO_NUMMER:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_set_konto_nummer_1_svc;
		break;

	case KNTO_SET_BLZ:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_set_blz_1_svc;
		break;

	case KNTO_SET_BANKNAME:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_set_bankname_1_svc;
		break;

	case KNTO_SET_BETRAG:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_set_betrag_1_svc;
		break;

	case KNTO_SET_KUNDE:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_set_kunde_1_svc;
		break;

	case KNTO_SET_UNASSIGNED:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_set_unassigned_1_svc;
		break;

	case KNTO_GET_KUNDE:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_get_kunde_1_svc;
		break;

	case KNTO_GET_KONTO_NUMMER:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_get_konto_nummer_1_svc;
		break;

	case KNTO_GET_BLZ:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_get_blz_1_svc;
		break;

	case KNTO_GET_BANKNAME:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_get_bankname_1_svc;
		break;

	case KNTO_GET_BETRAG:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_get_betrag_1_svc;
		break;

	case KNTO_EINZAHLEN:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_einzahlen_1_svc;
		break;

	case KNTO_AUSZAHLEN:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_auszahlen_1_svc;
		break;

	case KNTO_FIND_BY_KEY:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_find_by_key_1_svc;
		break;

	case KNTO_FIND_BY_KUNDE:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_find_by_kunde_1_svc;
		break;

	case KNTO_FIND_UNASSIGNED:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_find_unassigned_1_svc;
		break;

	case KNTO_GET_RID:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_get_rid_1_svc;
		break;

	case KNTO_REGISTER:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_register_1_svc;
		break;

	case KNTO_UNREGISTER:
		xdr_argument = (xdrproc_t) xdr_rknt;
		xdr_result = (xdrproc_t) xdr_rknt;
		local = (char *(*)(char *, struct svc_req *)) knto_unregister_1_svc;
		break;

	case DBMS_COMMIT:
		xdr_argument = (xdrproc_t) xdr_wrapstring;
		xdr_result = (xdrproc_t) xdr_short;
		local = (char *(*)(char *, struct svc_req *)) dbms_commit_1_svc;
		break;

	case DBMS_ROLLBACK:
		xdr_argument = (xdrproc_t) xdr_wrapstring;
		xdr_result = (xdrproc_t) xdr_short;
		local = (char *(*)(char *, struct svc_req *)) dbms_rollback_1_svc;
		break;

	case DBMS_DATA_SERVER_CHANGED:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_short;
		local = (char *(*)(char *, struct svc_req *)) dbms_data_server_changed_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		fprintf(stderr, "unable to free arguments");
		exit(1);
	}
	return;
}

int
rpcgen_main(int argc, char **argv)
{
	register SVCXPRT *transp;

	(void) pmap_unset(R_KNTO, R_KNTO_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf(stderr, "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, R_KNTO, R_KNTO_VERSION, r_knto_1, IPPROTO_UDP)) {
		fprintf(stderr, "unable to register (R_KNTO, R_KNTO_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf(stderr, "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, R_KNTO, R_KNTO_VERSION, r_knto_1, IPPROTO_TCP)) {
		fprintf(stderr, "unable to register (R_KNTO, R_KNTO_VERSION, tcp).");
		exit(1);
	}

	svc_run();
	fprintf(stderr, "svc_run returned");
	exit(1);
	/* NOTREACHED */
}
