/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "r_knto.h"

bool_t
xdr_rknt(XDR *xdrs, rknt *objp)
{

	 register long *buf;


	 if (xdrs->x_op == XDR_ENCODE) {
	 if (!xdr_long(xdrs, &objp->oid)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->cid, MAX_CIDLENGTH)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,5 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_long(xdrs, &objp->kunde_oid)) {
			 return (FALSE);
		 }
		 if (!xdr_long(xdrs, &objp->kunde_rid)) {
			 return (FALSE);
		 }
		 if (!xdr_long(xdrs, &objp->konto_id)) {
			 return (FALSE);
		 }
		 if (!xdr_long(xdrs, &objp->konto_nummer)) {
			 return (FALSE);
		 }
		 if (!xdr_long(xdrs, &objp->blz)) {
			 return (FALSE);
		 }

	  }
	  else {
		 IXDR_PUT_LONG(buf,objp->kunde_oid);
		 IXDR_PUT_LONG(buf,objp->kunde_rid);
		 IXDR_PUT_LONG(buf,objp->konto_id);
		 IXDR_PUT_LONG(buf,objp->konto_nummer);
		 IXDR_PUT_LONG(buf,objp->blz);
	  }
	 if (!xdr_string(xdrs, &objp->bankname, MAX_BANKNAME)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->list_of_knto.list_of_knto_val, (u_int *)&objp->list_of_knto.list_of_knto_len, ~0, sizeof(long), (xdrproc_t)xdr_long)) {
		 return (FALSE);
	 }
	 if (!xdr_double(xdrs, &objp->betrag)) {
		 return (FALSE);
	 }
	 if (!xdr_long(xdrs, &objp->rid)) {
		 return (FALSE);
	 }
	 if (!xdr_short(xdrs, &objp->rc)) {
		 return (FALSE);
	 }

 	 return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
	 if (!xdr_long(xdrs, &objp->oid)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->cid, MAX_CIDLENGTH)) {
		 return (FALSE);
	 }
	 buf = XDR_INLINE(xdrs,5 * BYTES_PER_XDR_UNIT);
	   if (buf == NULL) {
		 if (!xdr_long(xdrs, &objp->kunde_oid)) {
			 return (FALSE);
		 }
		 if (!xdr_long(xdrs, &objp->kunde_rid)) {
			 return (FALSE);
		 }
		 if (!xdr_long(xdrs, &objp->konto_id)) {
			 return (FALSE);
		 }
		 if (!xdr_long(xdrs, &objp->konto_nummer)) {
			 return (FALSE);
		 }
		 if (!xdr_long(xdrs, &objp->blz)) {
			 return (FALSE);
		 }

	  }
	  else {
		 objp->kunde_oid = IXDR_GET_LONG(buf);
		 objp->kunde_rid = IXDR_GET_LONG(buf);
		 objp->konto_id = IXDR_GET_LONG(buf);
		 objp->konto_nummer = IXDR_GET_LONG(buf);
		 objp->blz = IXDR_GET_LONG(buf);
	  }
	 if (!xdr_string(xdrs, &objp->bankname, MAX_BANKNAME)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->list_of_knto.list_of_knto_val, (u_int *)&objp->list_of_knto.list_of_knto_len, ~0, sizeof(long), (xdrproc_t)xdr_long)) {
		 return (FALSE);
	 }
	 if (!xdr_double(xdrs, &objp->betrag)) {
		 return (FALSE);
	 }
	 if (!xdr_long(xdrs, &objp->rid)) {
		 return (FALSE);
	 }
	 if (!xdr_short(xdrs, &objp->rc)) {
		 return (FALSE);
	 }
	 return(TRUE);
	}

	 if (!xdr_long(xdrs, &objp->oid)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->cid, MAX_CIDLENGTH)) {
		 return (FALSE);
	 }
	 if (!xdr_long(xdrs, &objp->kunde_oid)) {
		 return (FALSE);
	 }
	 if (!xdr_long(xdrs, &objp->kunde_rid)) {
		 return (FALSE);
	 }
	 if (!xdr_long(xdrs, &objp->konto_id)) {
		 return (FALSE);
	 }
	 if (!xdr_long(xdrs, &objp->konto_nummer)) {
		 return (FALSE);
	 }
	 if (!xdr_long(xdrs, &objp->blz)) {
		 return (FALSE);
	 }
	 if (!xdr_string(xdrs, &objp->bankname, MAX_BANKNAME)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->list_of_knto.list_of_knto_val, (u_int *)&objp->list_of_knto.list_of_knto_len, ~0, sizeof(long), (xdrproc_t)xdr_long)) {
		 return (FALSE);
	 }
	 if (!xdr_double(xdrs, &objp->betrag)) {
		 return (FALSE);
	 }
	 if (!xdr_long(xdrs, &objp->rid)) {
		 return (FALSE);
	 }
	 if (!xdr_short(xdrs, &objp->rc)) {
		 return (FALSE);
	 }
	return (TRUE);
}
