/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _R_BROK_H_RPCGEN
#define _R_BROK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_PROTO 4

struct r_bent {
	char *host;
	char *svcn;
	char *proto;
	long prgnr;
	long versnr;
};
typedef struct r_bent r_bent;

struct r_cid {
	char *cid;
};
typedef struct r_cid r_cid;

#include "brok.h"

#define R_BROK_PROTO "tcp"

 /* fuer CID */
#include "cent.h"

int rpcgen_main();

 /* Enthaelt nur '\0' */
extern char xdr_required_nullstring;


#define R_BROK 0x32132435
#define R_BROK_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define BROK_REGISTER 1
extern  int * brok_register_1(r_bent *, CLIENT *);
extern  int * brok_register_1_svc(r_bent *, struct svc_req *);
#define BROK_UNREGISTER 2
extern  int * brok_unregister_1(char **, CLIENT *);
extern  int * brok_unregister_1_svc(char **, struct svc_req *);
#define BROK_BIND 3
extern  r_bent * brok_bind_1(char **, CLIENT *);
extern  r_bent * brok_bind_1_svc(char **, struct svc_req *);
#define BROK_GET_CID 4
extern  r_cid * brok_get_cid_1(void *, CLIENT *);
extern  r_cid * brok_get_cid_1_svc(void *, struct svc_req *);
extern int r_brok_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define BROK_REGISTER 1
extern  int * brok_register_1();
extern  int * brok_register_1_svc();
#define BROK_UNREGISTER 2
extern  int * brok_unregister_1();
extern  int * brok_unregister_1_svc();
#define BROK_BIND 3
extern  r_bent * brok_bind_1();
extern  r_bent * brok_bind_1_svc();
#define BROK_GET_CID 4
extern  r_cid * brok_get_cid_1();
extern  r_cid * brok_get_cid_1_svc();
extern int r_brok_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_r_bent (XDR *, r_bent*);
extern  bool_t xdr_r_cid (XDR *, r_cid*);

#else /* K&R C */
extern bool_t xdr_r_bent ();
extern bool_t xdr_r_cid ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_R_BROK_H_RPCGEN */
