/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _R_BTAB_H_RPCGEN
#define _R_BTAB_H_RPCGEN

#include <rpc/rpc.h>

#define MAX_PATH 256
#define MAX_RECORD 8192

struct rtab {
	long oid;
	char *cid;
	char *path;
	char *record;
	long base_param;
	long rid;
	short rc;
	int rec_length_param;
};
typedef struct rtab rtab;
#ifdef __cplusplus 
extern "C" bool_t xdr_rtab(XDR *, rtab*);
#elif __STDC__ 
extern  bool_t xdr_rtab(XDR *, rtab*);
#else /* Old Style C */ 
bool_t xdr_rtab();
#endif /* Old Style C */ 

 /* Programmnummern fuer Kunden und Konten Btabs ... */
#define R_BTAB_KNDE 0x33132435
#define R_BTAB_KNTO 0x33132436

#include "btab.h"

#include "cent.h"

#define R_BTAB_PROTO "tcp"

extern CLIENT * pBtabServerHandle;


   /* main wird in rpcgen_main umbenannt */
int rpcgen_main ();

void btab_clnt_stub_chge_svcn (char * svcn);

   /* Enthaelt nur '\0' */
extern char xdr_required_nullstring;

   /* Fuelle rtab mit \0 */
   /* XDR_STRING() benoetigt gueltige Zeiger (nicht NULL) */
#define rtab_init(r) memset ((r), '\0', sizeof (rtab));              (r)->record = &xdr_required_nullstring;             (r)->path =  &xdr_required_nullstring;              (r)->cid =  &xdr_required_nullstring;


#define R_BTAB ((u_long)0x32132434)
#define R_BTAB_VERSION ((u_long)1)

#ifdef __cplusplus
#define BTAB_NEW ((u_long)1)
extern "C" rtab * btab_new_1(rtab *, CLIENT *);
extern "C" rtab * btab_new_1_svc(rtab *, struct svc_req *);
#define BTAB_INIT ((u_long)2)
extern "C" rtab * btab_init_1(rtab *, CLIENT *);
extern "C" rtab * btab_init_1_svc(rtab *, struct svc_req *);
#define BTAB_CLEAR ((u_long)3)
extern "C" rtab * btab_clear_1(rtab *, CLIENT *);
extern "C" rtab * btab_clear_1_svc(rtab *, struct svc_req *);
#define BTAB_DELETE ((u_long)4)
extern "C" rtab * btab_delete_1(rtab *, CLIENT *);
extern "C" rtab * btab_delete_1_svc(rtab *, struct svc_req *);
#define BTAB_OPEN ((u_long)5)
extern "C" rtab * btab_open_1(rtab *, CLIENT *);
extern "C" rtab * btab_open_1_svc(rtab *, struct svc_req *);
#define BTAB_CLOSE ((u_long)6)
extern "C" rtab * btab_close_1(rtab *, CLIENT *);
extern "C" rtab * btab_close_1_svc(rtab *, struct svc_req *);
#define BTAB_REWIND ((u_long)7)
extern "C" rtab * btab_rewind_1(rtab *, CLIENT *);
extern "C" rtab * btab_rewind_1_svc(rtab *, struct svc_req *);
#define BTAB_GET_NEXT ((u_long)8)
extern "C" rtab * btab_get_next_1(rtab *, CLIENT *);
extern "C" rtab * btab_get_next_1_svc(rtab *, struct svc_req *);
#define BTAB_GET_PREVIOUS ((u_long)9)
extern "C" rtab * btab_get_previous_1(rtab *, CLIENT *);
extern "C" rtab * btab_get_previous_1_svc(rtab *, struct svc_req *);
#define BTAB_GET_AT ((u_long)10)
extern "C" rtab * btab_get_at_1(rtab *, CLIENT *);
extern "C" rtab * btab_get_at_1_svc(rtab *, struct svc_req *);
#define BTAB_PUT_AT ((u_long)11)
extern "C" rtab * btab_put_at_1(rtab *, CLIENT *);
extern "C" rtab * btab_put_at_1_svc(rtab *, struct svc_req *);
#define BTAB_APPEND ((u_long)12)
extern "C" rtab * btab_append_1(rtab *, CLIENT *);
extern "C" rtab * btab_append_1_svc(rtab *, struct svc_req *);
#define BTAB_IS_EMPTY ((u_long)13)
extern "C" short * btab_is_empty_1(rtab *, CLIENT *);
extern "C" short * btab_is_empty_1_svc(rtab *, struct svc_req *);
#define BTAB_IS_NOT_EMPTY ((u_long)14)
extern "C" short * btab_is_not_empty_1(rtab *, CLIENT *);
extern "C" short * btab_is_not_empty_1_svc(rtab *, struct svc_req *);

#elif __STDC__
#define BTAB_NEW ((u_long)1)
extern  rtab * btab_new_1(rtab *, CLIENT *);
extern  rtab * btab_new_1_svc(rtab *, struct svc_req *);
#define BTAB_INIT ((u_long)2)
extern  rtab * btab_init_1(rtab *, CLIENT *);
extern  rtab * btab_init_1_svc(rtab *, struct svc_req *);
#define BTAB_CLEAR ((u_long)3)
extern  rtab * btab_clear_1(rtab *, CLIENT *);
extern  rtab * btab_clear_1_svc(rtab *, struct svc_req *);
#define BTAB_DELETE ((u_long)4)
extern  rtab * btab_delete_1(rtab *, CLIENT *);
extern  rtab * btab_delete_1_svc(rtab *, struct svc_req *);
#define BTAB_OPEN ((u_long)5)
extern  rtab * btab_open_1(rtab *, CLIENT *);
extern  rtab * btab_open_1_svc(rtab *, struct svc_req *);
#define BTAB_CLOSE ((u_long)6)
extern  rtab * btab_close_1(rtab *, CLIENT *);
extern  rtab * btab_close_1_svc(rtab *, struct svc_req *);
#define BTAB_REWIND ((u_long)7)
extern  rtab * btab_rewind_1(rtab *, CLIENT *);
extern  rtab * btab_rewind_1_svc(rtab *, struct svc_req *);
#define BTAB_GET_NEXT ((u_long)8)
extern  rtab * btab_get_next_1(rtab *, CLIENT *);
extern  rtab * btab_get_next_1_svc(rtab *, struct svc_req *);
#define BTAB_GET_PREVIOUS ((u_long)9)
extern  rtab * btab_get_previous_1(rtab *, CLIENT *);
extern  rtab * btab_get_previous_1_svc(rtab *, struct svc_req *);
#define BTAB_GET_AT ((u_long)10)
extern  rtab * btab_get_at_1(rtab *, CLIENT *);
extern  rtab * btab_get_at_1_svc(rtab *, struct svc_req *);
#define BTAB_PUT_AT ((u_long)11)
extern  rtab * btab_put_at_1(rtab *, CLIENT *);
extern  rtab * btab_put_at_1_svc(rtab *, struct svc_req *);
#define BTAB_APPEND ((u_long)12)
extern  rtab * btab_append_1(rtab *, CLIENT *);
extern  rtab * btab_append_1_svc(rtab *, struct svc_req *);
#define BTAB_IS_EMPTY ((u_long)13)
extern  short * btab_is_empty_1(rtab *, CLIENT *);
extern  short * btab_is_empty_1_svc(rtab *, struct svc_req *);
#define BTAB_IS_NOT_EMPTY ((u_long)14)
extern  short * btab_is_not_empty_1(rtab *, CLIENT *);
extern  short * btab_is_not_empty_1_svc(rtab *, struct svc_req *);

#else /* Old Style C */ 
#define BTAB_NEW ((u_long)1)
extern  rtab * btab_new_1();
extern  rtab * btab_new_1_svc();
#define BTAB_INIT ((u_long)2)
extern  rtab * btab_init_1();
extern  rtab * btab_init_1_svc();
#define BTAB_CLEAR ((u_long)3)
extern  rtab * btab_clear_1();
extern  rtab * btab_clear_1_svc();
#define BTAB_DELETE ((u_long)4)
extern  rtab * btab_delete_1();
extern  rtab * btab_delete_1_svc();
#define BTAB_OPEN ((u_long)5)
extern  rtab * btab_open_1();
extern  rtab * btab_open_1_svc();
#define BTAB_CLOSE ((u_long)6)
extern  rtab * btab_close_1();
extern  rtab * btab_close_1_svc();
#define BTAB_REWIND ((u_long)7)
extern  rtab * btab_rewind_1();
extern  rtab * btab_rewind_1_svc();
#define BTAB_GET_NEXT ((u_long)8)
extern  rtab * btab_get_next_1();
extern  rtab * btab_get_next_1_svc();
#define BTAB_GET_PREVIOUS ((u_long)9)
extern  rtab * btab_get_previous_1();
extern  rtab * btab_get_previous_1_svc();
#define BTAB_GET_AT ((u_long)10)
extern  rtab * btab_get_at_1();
extern  rtab * btab_get_at_1_svc();
#define BTAB_PUT_AT ((u_long)11)
extern  rtab * btab_put_at_1();
extern  rtab * btab_put_at_1_svc();
#define BTAB_APPEND ((u_long)12)
extern  rtab * btab_append_1();
extern  rtab * btab_append_1_svc();
#define BTAB_IS_EMPTY ((u_long)13)
extern  short * btab_is_empty_1();
extern  short * btab_is_empty_1_svc();
#define BTAB_IS_NOT_EMPTY ((u_long)14)
extern  short * btab_is_not_empty_1();
extern  short * btab_is_not_empty_1_svc();
#endif /* Old Style C */ 

#endif /* !_R_BTAB_H_RPCGEN */
