/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _R_KNTO_H_RPCGEN
#define _R_KNTO_H_RPCGEN

#include <rpc/rpc.h>


struct rknt {
	long oid;
	char *cid;
	long kunde_oid;
	long kunde_rid;
	long konto_id;
	long konto_nummer;
	long blz;
	char *bankname;
	struct {
		u_int list_of_knto_len;
		long *list_of_knto_val;
	} list_of_knto;
	double betrag;
	long rid;
	short rc;
};
typedef struct rknt rknt;
#ifdef __cplusplus 
extern "C" bool_t xdr_rknt(XDR *, rknt*);
#elif __STDC__ 
extern  bool_t xdr_rknt(XDR *, rknt*);
#else /* Old Style C */ 
bool_t xdr_rknt();
#endif /* Old Style C */ 


#include "knto.h"
#include "cent.h"
#include "cmgr.h"

#define R_KNTO_PROTO "tcp"

int rpcgen_main ();

   /* Enthaelt nur '\0' */
extern char xdr_required_nullstring;

   /* Fuelle rknd mit \0 */
   /* XDR_STRING() benoetigt gueltige Zeiger (nicht NULL) */
#define rknt_init(r) memset ((r), '\0', sizeof (rknt));             (r)->bankname = &xdr_required_nullstring;                  (r)->cid      = &xdr_required_nullstring;


#define R_KNTO ((u_long)0x32132486)
#define R_KNTO_VERSION ((u_long)1)

#ifdef __cplusplus
#define KNTO_NEW ((u_long)1)
extern "C" rknt * knto_new_1(rknt *, CLIENT *);
extern "C" rknt * knto_new_1_svc(rknt *, struct svc_req *);
#define KNTO_INIT ((u_long)2)
extern "C" rknt * knto_init_1(rknt *, CLIENT *);
extern "C" rknt * knto_init_1_svc(rknt *, struct svc_req *);
#define KNTO_CLEAR ((u_long)3)
extern "C" rknt * knto_clear_1(rknt *, CLIENT *);
extern "C" rknt * knto_clear_1_svc(rknt *, struct svc_req *);
#define KNTO_DELETE ((u_long)4)
extern "C" rknt * knto_delete_1(rknt *, CLIENT *);
extern "C" rknt * knto_delete_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_KONTO_NUMMER ((u_long)5)
extern "C" rknt * knto_set_konto_nummer_1(rknt *, CLIENT *);
extern "C" rknt * knto_set_konto_nummer_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_BLZ ((u_long)6)
extern "C" rknt * knto_set_blz_1(rknt *, CLIENT *);
extern "C" rknt * knto_set_blz_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_BANKNAME ((u_long)7)
extern "C" rknt * knto_set_bankname_1(rknt *, CLIENT *);
extern "C" rknt * knto_set_bankname_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_BETRAG ((u_long)8)
extern "C" rknt * knto_set_betrag_1(rknt *, CLIENT *);
extern "C" rknt * knto_set_betrag_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_KUNDE ((u_long)9)
extern "C" rknt * knto_set_kunde_1(rknt *, CLIENT *);
extern "C" rknt * knto_set_kunde_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_UNASSIGNED ((u_long)10)
extern "C" rknt * knto_set_unassigned_1(rknt *, CLIENT *);
extern "C" rknt * knto_set_unassigned_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_KUNDE ((u_long)11)
extern "C" rknt * knto_get_kunde_1(rknt *, CLIENT *);
extern "C" rknt * knto_get_kunde_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_KONTO_NUMMER ((u_long)12)
extern "C" rknt * knto_get_konto_nummer_1(rknt *, CLIENT *);
extern "C" rknt * knto_get_konto_nummer_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_BLZ ((u_long)13)
extern "C" rknt * knto_get_blz_1(rknt *, CLIENT *);
extern "C" rknt * knto_get_blz_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_BANKNAME ((u_long)14)
extern "C" rknt * knto_get_bankname_1(rknt *, CLIENT *);
extern "C" rknt * knto_get_bankname_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_BETRAG ((u_long)15)
extern "C" rknt * knto_get_betrag_1(rknt *, CLIENT *);
extern "C" rknt * knto_get_betrag_1_svc(rknt *, struct svc_req *);
#define KNTO_EINZAHLEN ((u_long)16)
extern "C" rknt * knto_einzahlen_1(rknt *, CLIENT *);
extern "C" rknt * knto_einzahlen_1_svc(rknt *, struct svc_req *);
#define KNTO_AUSZAHLEN ((u_long)17)
extern "C" rknt * knto_auszahlen_1(rknt *, CLIENT *);
extern "C" rknt * knto_auszahlen_1_svc(rknt *, struct svc_req *);
#define KNTO_FIND_BY_KEY ((u_long)18)
extern "C" rknt * knto_find_by_key_1(rknt *, CLIENT *);
extern "C" rknt * knto_find_by_key_1_svc(rknt *, struct svc_req *);
#define KNTO_FIND_BY_KUNDE ((u_long)19)
extern "C" rknt * knto_find_by_kunde_1(rknt *, CLIENT *);
extern "C" rknt * knto_find_by_kunde_1_svc(rknt *, struct svc_req *);
#define KNTO_FIND_UNASSIGNED ((u_long)20)
extern "C" rknt * knto_find_unassigned_1(rknt *, CLIENT *);
extern "C" rknt * knto_find_unassigned_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_RID ((u_long)21)
extern "C" rknt * knto_get_rid_1(rknt *, CLIENT *);
extern "C" rknt * knto_get_rid_1_svc(rknt *, struct svc_req *);
#define KNTO_REGISTER ((u_long)22)
extern "C" rknt * knto_register_1(rknt *, CLIENT *);
extern "C" rknt * knto_register_1_svc(rknt *, struct svc_req *);
#define KNTO_UNREGISTER ((u_long)23)
extern "C" rknt * knto_unregister_1(rknt *, CLIENT *);
extern "C" rknt * knto_unregister_1_svc(rknt *, struct svc_req *);
#define DBMS_COMMIT ((u_long)100)
extern "C" short * dbms_commit_1(char **, CLIENT *);
extern "C" short * dbms_commit_1_svc(char **, struct svc_req *);
#define DBMS_ROLLBACK ((u_long)101)
extern "C" short * dbms_rollback_1(char **, CLIENT *);
extern "C" short * dbms_rollback_1_svc(char **, struct svc_req *);
#define DBMS_DATA_SERVER_CHANGED ((u_long)102)
extern "C" short * dbms_data_server_changed_1(void *, CLIENT *);
extern "C" short * dbms_data_server_changed_1_svc(void *, struct svc_req *);

#elif __STDC__
#define KNTO_NEW ((u_long)1)
extern  rknt * knto_new_1(rknt *, CLIENT *);
extern  rknt * knto_new_1_svc(rknt *, struct svc_req *);
#define KNTO_INIT ((u_long)2)
extern  rknt * knto_init_1(rknt *, CLIENT *);
extern  rknt * knto_init_1_svc(rknt *, struct svc_req *);
#define KNTO_CLEAR ((u_long)3)
extern  rknt * knto_clear_1(rknt *, CLIENT *);
extern  rknt * knto_clear_1_svc(rknt *, struct svc_req *);
#define KNTO_DELETE ((u_long)4)
extern  rknt * knto_delete_1(rknt *, CLIENT *);
extern  rknt * knto_delete_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_KONTO_NUMMER ((u_long)5)
extern  rknt * knto_set_konto_nummer_1(rknt *, CLIENT *);
extern  rknt * knto_set_konto_nummer_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_BLZ ((u_long)6)
extern  rknt * knto_set_blz_1(rknt *, CLIENT *);
extern  rknt * knto_set_blz_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_BANKNAME ((u_long)7)
extern  rknt * knto_set_bankname_1(rknt *, CLIENT *);
extern  rknt * knto_set_bankname_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_BETRAG ((u_long)8)
extern  rknt * knto_set_betrag_1(rknt *, CLIENT *);
extern  rknt * knto_set_betrag_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_KUNDE ((u_long)9)
extern  rknt * knto_set_kunde_1(rknt *, CLIENT *);
extern  rknt * knto_set_kunde_1_svc(rknt *, struct svc_req *);
#define KNTO_SET_UNASSIGNED ((u_long)10)
extern  rknt * knto_set_unassigned_1(rknt *, CLIENT *);
extern  rknt * knto_set_unassigned_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_KUNDE ((u_long)11)
extern  rknt * knto_get_kunde_1(rknt *, CLIENT *);
extern  rknt * knto_get_kunde_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_KONTO_NUMMER ((u_long)12)
extern  rknt * knto_get_konto_nummer_1(rknt *, CLIENT *);
extern  rknt * knto_get_konto_nummer_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_BLZ ((u_long)13)
extern  rknt * knto_get_blz_1(rknt *, CLIENT *);
extern  rknt * knto_get_blz_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_BANKNAME ((u_long)14)
extern  rknt * knto_get_bankname_1(rknt *, CLIENT *);
extern  rknt * knto_get_bankname_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_BETRAG ((u_long)15)
extern  rknt * knto_get_betrag_1(rknt *, CLIENT *);
extern  rknt * knto_get_betrag_1_svc(rknt *, struct svc_req *);
#define KNTO_EINZAHLEN ((u_long)16)
extern  rknt * knto_einzahlen_1(rknt *, CLIENT *);
extern  rknt * knto_einzahlen_1_svc(rknt *, struct svc_req *);
#define KNTO_AUSZAHLEN ((u_long)17)
extern  rknt * knto_auszahlen_1(rknt *, CLIENT *);
extern  rknt * knto_auszahlen_1_svc(rknt *, struct svc_req *);
#define KNTO_FIND_BY_KEY ((u_long)18)
extern  rknt * knto_find_by_key_1(rknt *, CLIENT *);
extern  rknt * knto_find_by_key_1_svc(rknt *, struct svc_req *);
#define KNTO_FIND_BY_KUNDE ((u_long)19)
extern  rknt * knto_find_by_kunde_1(rknt *, CLIENT *);
extern  rknt * knto_find_by_kunde_1_svc(rknt *, struct svc_req *);
#define KNTO_FIND_UNASSIGNED ((u_long)20)
extern  rknt * knto_find_unassigned_1(rknt *, CLIENT *);
extern  rknt * knto_find_unassigned_1_svc(rknt *, struct svc_req *);
#define KNTO_GET_RID ((u_long)21)
extern  rknt * knto_get_rid_1(rknt *, CLIENT *);
extern  rknt * knto_get_rid_1_svc(rknt *, struct svc_req *);
#define KNTO_REGISTER ((u_long)22)
extern  rknt * knto_register_1(rknt *, CLIENT *);
extern  rknt * knto_register_1_svc(rknt *, struct svc_req *);
#define KNTO_UNREGISTER ((u_long)23)
extern  rknt * knto_unregister_1(rknt *, CLIENT *);
extern  rknt * knto_unregister_1_svc(rknt *, struct svc_req *);
#define DBMS_COMMIT ((u_long)100)
extern  short * dbms_commit_1(char **, CLIENT *);
extern  short * dbms_commit_1_svc(char **, struct svc_req *);
#define DBMS_ROLLBACK ((u_long)101)
extern  short * dbms_rollback_1(char **, CLIENT *);
extern  short * dbms_rollback_1_svc(char **, struct svc_req *);
#define DBMS_DATA_SERVER_CHANGED ((u_long)102)
extern  short * dbms_data_server_changed_1(void *, CLIENT *);
extern  short * dbms_data_server_changed_1_svc(void *, struct svc_req *);

#else /* Old Style C */ 
#define KNTO_NEW ((u_long)1)
extern  rknt * knto_new_1();
extern  rknt * knto_new_1_svc();
#define KNTO_INIT ((u_long)2)
extern  rknt * knto_init_1();
extern  rknt * knto_init_1_svc();
#define KNTO_CLEAR ((u_long)3)
extern  rknt * knto_clear_1();
extern  rknt * knto_clear_1_svc();
#define KNTO_DELETE ((u_long)4)
extern  rknt * knto_delete_1();
extern  rknt * knto_delete_1_svc();
#define KNTO_SET_KONTO_NUMMER ((u_long)5)
extern  rknt * knto_set_konto_nummer_1();
extern  rknt * knto_set_konto_nummer_1_svc();
#define KNTO_SET_BLZ ((u_long)6)
extern  rknt * knto_set_blz_1();
extern  rknt * knto_set_blz_1_svc();
#define KNTO_SET_BANKNAME ((u_long)7)
extern  rknt * knto_set_bankname_1();
extern  rknt * knto_set_bankname_1_svc();
#define KNTO_SET_BETRAG ((u_long)8)
extern  rknt * knto_set_betrag_1();
extern  rknt * knto_set_betrag_1_svc();
#define KNTO_SET_KUNDE ((u_long)9)
extern  rknt * knto_set_kunde_1();
extern  rknt * knto_set_kunde_1_svc();
#define KNTO_SET_UNASSIGNED ((u_long)10)
extern  rknt * knto_set_unassigned_1();
extern  rknt * knto_set_unassigned_1_svc();
#define KNTO_GET_KUNDE ((u_long)11)
extern  rknt * knto_get_kunde_1();
extern  rknt * knto_get_kunde_1_svc();
#define KNTO_GET_KONTO_NUMMER ((u_long)12)
extern  rknt * knto_get_konto_nummer_1();
extern  rknt * knto_get_konto_nummer_1_svc();
#define KNTO_GET_BLZ ((u_long)13)
extern  rknt * knto_get_blz_1();
extern  rknt * knto_get_blz_1_svc();
#define KNTO_GET_BANKNAME ((u_long)14)
extern  rknt * knto_get_bankname_1();
extern  rknt * knto_get_bankname_1_svc();
#define KNTO_GET_BETRAG ((u_long)15)
extern  rknt * knto_get_betrag_1();
extern  rknt * knto_get_betrag_1_svc();
#define KNTO_EINZAHLEN ((u_long)16)
extern  rknt * knto_einzahlen_1();
extern  rknt * knto_einzahlen_1_svc();
#define KNTO_AUSZAHLEN ((u_long)17)
extern  rknt * knto_auszahlen_1();
extern  rknt * knto_auszahlen_1_svc();
#define KNTO_FIND_BY_KEY ((u_long)18)
extern  rknt * knto_find_by_key_1();
extern  rknt * knto_find_by_key_1_svc();
#define KNTO_FIND_BY_KUNDE ((u_long)19)
extern  rknt * knto_find_by_kunde_1();
extern  rknt * knto_find_by_kunde_1_svc();
#define KNTO_FIND_UNASSIGNED ((u_long)20)
extern  rknt * knto_find_unassigned_1();
extern  rknt * knto_find_unassigned_1_svc();
#define KNTO_GET_RID ((u_long)21)
extern  rknt * knto_get_rid_1();
extern  rknt * knto_get_rid_1_svc();
#define KNTO_REGISTER ((u_long)22)
extern  rknt * knto_register_1();
extern  rknt * knto_register_1_svc();
#define KNTO_UNREGISTER ((u_long)23)
extern  rknt * knto_unregister_1();
extern  rknt * knto_unregister_1_svc();
#define DBMS_COMMIT ((u_long)100)
extern  short * dbms_commit_1();
extern  short * dbms_commit_1_svc();
#define DBMS_ROLLBACK ((u_long)101)
extern  short * dbms_rollback_1();
extern  short * dbms_rollback_1_svc();
#define DBMS_DATA_SERVER_CHANGED ((u_long)102)
extern  short * dbms_data_server_changed_1();
extern  short * dbms_data_server_changed_1_svc();
#endif /* Old Style C */ 

#endif /* !_R_KNTO_H_RPCGEN */
