/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _R_KNDE_H_RPCGEN
#define _R_KNDE_H_RPCGEN

#include <rpc/rpc.h>

#define MAX_ANREDE 10

struct radrs {
	char *strasse;
	char *hausnr;
	char *plz;
	char *ort;
	char *land;
};
typedef struct radrs radrs;
#ifdef __cplusplus 
extern "C" bool_t xdr_radrs(XDR *, radrs*);
#elif __STDC__ 
extern  bool_t xdr_radrs(XDR *, radrs*);
#else /* Old Style C */ 
bool_t xdr_radrs();
#endif /* Old Style C */ 


struct rknd {
	long oid;
	char *cid;
	char *name;
	char *vorname;
	char *anrede;
	struct {
		u_int list_of_konten_len;
		long *list_of_konten_val;
	} list_of_konten;
	radrs adresse;
	long rid;
	short rc;
};
typedef struct rknd rknd;
#ifdef __cplusplus 
extern "C" bool_t xdr_rknd(XDR *, rknd*);
#elif __STDC__ 
extern  bool_t xdr_rknd(XDR *, rknd*);
#else /* Old Style C */ 
bool_t xdr_rknd();
#endif /* Old Style C */ 


#include "knde.h"
#include "adrs.h"
#include "enum.h"
#include "cent.h"

#define R_KNDE_PROTO "tcp"

int rpcgen_main ();

   /* Enthaelt nur '\0' */
extern char xdr_required_nullstring;

   /* Fuelle rknd mit \0 */
   /* XDR_STRING() benoetigt gueltige Zeiger (nicht NULL) */
#define rknd_init(r) memset ((r), '\0', sizeof (rknd));                         (r)->name                 = &xdr_required_nullstring;                  (r)->vorname              = &xdr_required_nullstring;                  (r)->cid                  = &xdr_required_nullstring;                  (r)->anrede               = &xdr_required_nullstring;                  (r)->adresse.strasse      = &xdr_required_nullstring;                  (r)->adresse.hausnr       = &xdr_required_nullstring;                  (r)->adresse.plz          = &xdr_required_nullstring;                  (r)->adresse.ort          = &xdr_required_nullstring;                  (r)->adresse.land         = &xdr_required_nullstring;


#define R_KNDE ((u_long)0x32132484)
#define R_KNDE_VERSION ((u_long)1)

#ifdef __cplusplus
#define KNDE_NEW ((u_long)1)
extern "C" rknd * knde_new_1(rknd *, CLIENT *);
extern "C" rknd * knde_new_1_svc(rknd *, struct svc_req *);
#define KNDE_INIT ((u_long)2)
extern "C" rknd * knde_init_1(rknd *, CLIENT *);
extern "C" rknd * knde_init_1_svc(rknd *, struct svc_req *);
#define KNDE_CLEAR ((u_long)3)
extern "C" rknd * knde_clear_1(rknd *, CLIENT *);
extern "C" rknd * knde_clear_1_svc(rknd *, struct svc_req *);
#define KNDE_DELETE ((u_long)4)
extern "C" rknd * knde_delete_1(rknd *, CLIENT *);
extern "C" rknd * knde_delete_1_svc(rknd *, struct svc_req *);
#define KNDE_SET_NAME ((u_long)5)
extern "C" rknd * knde_set_name_1(rknd *, CLIENT *);
extern "C" rknd * knde_set_name_1_svc(rknd *, struct svc_req *);
#define KNDE_SET_VORNAME ((u_long)6)
extern "C" rknd * knde_set_vorname_1(rknd *, CLIENT *);
extern "C" rknd * knde_set_vorname_1_svc(rknd *, struct svc_req *);
#define KNDE_SET_ANREDE ((u_long)7)
extern "C" rknd * knde_set_anrede_1(rknd *, CLIENT *);
extern "C" rknd * knde_set_anrede_1_svc(rknd *, struct svc_req *);
#define KNDE_SET_ADRESSE ((u_long)8)
extern "C" rknd * knde_set_adresse_1(rknd *, CLIENT *);
extern "C" rknd * knde_set_adresse_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_NAME ((u_long)9)
extern "C" rknd * knde_get_name_1(rknd *, CLIENT *);
extern "C" rknd * knde_get_name_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_VORNAME ((u_long)10)
extern "C" rknd * knde_get_vorname_1(rknd *, CLIENT *);
extern "C" rknd * knde_get_vorname_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_RID ((u_long)11)
extern "C" rknd * knde_get_rid_1(rknd *, CLIENT *);
extern "C" rknd * knde_get_rid_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_KONTEN ((u_long)12)
extern "C" rknd * knde_get_konten_1(rknd *, CLIENT *);
extern "C" rknd * knde_get_konten_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_ANREDE ((u_long)13)
extern "C" rknd * knde_get_anrede_1(rknd *, CLIENT *);
extern "C" rknd * knde_get_anrede_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_ADRESSE ((u_long)14)
extern "C" rknd * knde_get_adresse_1(rknd *, CLIENT *);
extern "C" rknd * knde_get_adresse_1_svc(rknd *, struct svc_req *);
#define KNDE_FIND_BY_KEY ((u_long)15)
extern "C" rknd * knde_find_by_key_1(rknd *, CLIENT *);
extern "C" rknd * knde_find_by_key_1_svc(rknd *, struct svc_req *);
#define KNDE_REGISTER ((u_long)16)
extern "C" rknd * knde_register_1(rknd *, CLIENT *);
extern "C" rknd * knde_register_1_svc(rknd *, struct svc_req *);
#define KNDE_UNREGISTER ((u_long)17)
extern "C" rknd * knde_unregister_1(rknd *, CLIENT *);
extern "C" rknd * knde_unregister_1_svc(rknd *, struct svc_req *);
#define DBMS_COMMIT ((u_long)100)
extern "C" short * dbms_commit_1(char **, CLIENT *);
extern "C" short * dbms_commit_1_svc(char **, struct svc_req *);
#define DBMS_ROLLBACK ((u_long)101)
extern "C" short * dbms_rollback_1(char **, CLIENT *);
extern "C" short * dbms_rollback_1_svc(char **, struct svc_req *);
#define DBMS_DATA_SERVER_CHANGED ((u_long)102)
extern "C" short * dbms_data_server_changed_1(void *, CLIENT *);
extern "C" short * dbms_data_server_changed_1_svc(void *, struct svc_req *);

#elif __STDC__
#define KNDE_NEW ((u_long)1)
extern  rknd * knde_new_1(rknd *, CLIENT *);
extern  rknd * knde_new_1_svc(rknd *, struct svc_req *);
#define KNDE_INIT ((u_long)2)
extern  rknd * knde_init_1(rknd *, CLIENT *);
extern  rknd * knde_init_1_svc(rknd *, struct svc_req *);
#define KNDE_CLEAR ((u_long)3)
extern  rknd * knde_clear_1(rknd *, CLIENT *);
extern  rknd * knde_clear_1_svc(rknd *, struct svc_req *);
#define KNDE_DELETE ((u_long)4)
extern  rknd * knde_delete_1(rknd *, CLIENT *);
extern  rknd * knde_delete_1_svc(rknd *, struct svc_req *);
#define KNDE_SET_NAME ((u_long)5)
extern  rknd * knde_set_name_1(rknd *, CLIENT *);
extern  rknd * knde_set_name_1_svc(rknd *, struct svc_req *);
#define KNDE_SET_VORNAME ((u_long)6)
extern  rknd * knde_set_vorname_1(rknd *, CLIENT *);
extern  rknd * knde_set_vorname_1_svc(rknd *, struct svc_req *);
#define KNDE_SET_ANREDE ((u_long)7)
extern  rknd * knde_set_anrede_1(rknd *, CLIENT *);
extern  rknd * knde_set_anrede_1_svc(rknd *, struct svc_req *);
#define KNDE_SET_ADRESSE ((u_long)8)
extern  rknd * knde_set_adresse_1(rknd *, CLIENT *);
extern  rknd * knde_set_adresse_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_NAME ((u_long)9)
extern  rknd * knde_get_name_1(rknd *, CLIENT *);
extern  rknd * knde_get_name_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_VORNAME ((u_long)10)
extern  rknd * knde_get_vorname_1(rknd *, CLIENT *);
extern  rknd * knde_get_vorname_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_RID ((u_long)11)
extern  rknd * knde_get_rid_1(rknd *, CLIENT *);
extern  rknd * knde_get_rid_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_KONTEN ((u_long)12)
extern  rknd * knde_get_konten_1(rknd *, CLIENT *);
extern  rknd * knde_get_konten_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_ANREDE ((u_long)13)
extern  rknd * knde_get_anrede_1(rknd *, CLIENT *);
extern  rknd * knde_get_anrede_1_svc(rknd *, struct svc_req *);
#define KNDE_GET_ADRESSE ((u_long)14)
extern  rknd * knde_get_adresse_1(rknd *, CLIENT *);
extern  rknd * knde_get_adresse_1_svc(rknd *, struct svc_req *);
#define KNDE_FIND_BY_KEY ((u_long)15)
extern  rknd * knde_find_by_key_1(rknd *, CLIENT *);
extern  rknd * knde_find_by_key_1_svc(rknd *, struct svc_req *);
#define KNDE_REGISTER ((u_long)16)
extern  rknd * knde_register_1(rknd *, CLIENT *);
extern  rknd * knde_register_1_svc(rknd *, struct svc_req *);
#define KNDE_UNREGISTER ((u_long)17)
extern  rknd * knde_unregister_1(rknd *, CLIENT *);
extern  rknd * knde_unregister_1_svc(rknd *, struct svc_req *);
#define DBMS_COMMIT ((u_long)100)
extern  short * dbms_commit_1(char **, CLIENT *);
extern  short * dbms_commit_1_svc(char **, struct svc_req *);
#define DBMS_ROLLBACK ((u_long)101)
extern  short * dbms_rollback_1(char **, CLIENT *);
extern  short * dbms_rollback_1_svc(char **, struct svc_req *);
#define DBMS_DATA_SERVER_CHANGED ((u_long)102)
extern  short * dbms_data_server_changed_1(void *, CLIENT *);
extern  short * dbms_data_server_changed_1_svc(void *, struct svc_req *);

#else /* Old Style C */ 
#define KNDE_NEW ((u_long)1)
extern  rknd * knde_new_1();
extern  rknd * knde_new_1_svc();
#define KNDE_INIT ((u_long)2)
extern  rknd * knde_init_1();
extern  rknd * knde_init_1_svc();
#define KNDE_CLEAR ((u_long)3)
extern  rknd * knde_clear_1();
extern  rknd * knde_clear_1_svc();
#define KNDE_DELETE ((u_long)4)
extern  rknd * knde_delete_1();
extern  rknd * knde_delete_1_svc();
#define KNDE_SET_NAME ((u_long)5)
extern  rknd * knde_set_name_1();
extern  rknd * knde_set_name_1_svc();
#define KNDE_SET_VORNAME ((u_long)6)
extern  rknd * knde_set_vorname_1();
extern  rknd * knde_set_vorname_1_svc();
#define KNDE_SET_ANREDE ((u_long)7)
extern  rknd * knde_set_anrede_1();
extern  rknd * knde_set_anrede_1_svc();
#define KNDE_SET_ADRESSE ((u_long)8)
extern  rknd * knde_set_adresse_1();
extern  rknd * knde_set_adresse_1_svc();
#define KNDE_GET_NAME ((u_long)9)
extern  rknd * knde_get_name_1();
extern  rknd * knde_get_name_1_svc();
#define KNDE_GET_VORNAME ((u_long)10)
extern  rknd * knde_get_vorname_1();
extern  rknd * knde_get_vorname_1_svc();
#define KNDE_GET_RID ((u_long)11)
extern  rknd * knde_get_rid_1();
extern  rknd * knde_get_rid_1_svc();
#define KNDE_GET_KONTEN ((u_long)12)
extern  rknd * knde_get_konten_1();
extern  rknd * knde_get_konten_1_svc();
#define KNDE_GET_ANREDE ((u_long)13)
extern  rknd * knde_get_anrede_1();
extern  rknd * knde_get_anrede_1_svc();
#define KNDE_GET_ADRESSE ((u_long)14)
extern  rknd * knde_get_adresse_1();
extern  rknd * knde_get_adresse_1_svc();
#define KNDE_FIND_BY_KEY ((u_long)15)
extern  rknd * knde_find_by_key_1();
extern  rknd * knde_find_by_key_1_svc();
#define KNDE_REGISTER ((u_long)16)
extern  rknd * knde_register_1();
extern  rknd * knde_register_1_svc();
#define KNDE_UNREGISTER ((u_long)17)
extern  rknd * knde_unregister_1();
extern  rknd * knde_unregister_1_svc();
#define DBMS_COMMIT ((u_long)100)
extern  short * dbms_commit_1();
extern  short * dbms_commit_1_svc();
#define DBMS_ROLLBACK ((u_long)101)
extern  short * dbms_rollback_1();
extern  short * dbms_rollback_1_svc();
#define DBMS_DATA_SERVER_CHANGED ((u_long)102)
extern  short * dbms_data_server_changed_1();
extern  short * dbms_data_server_changed_1_svc();
#endif /* Old Style C */ 

#endif /* !_R_KNDE_H_RPCGEN */
