/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "r_knde.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

rknd *
knde_new_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_NEW, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_init_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_INIT, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_clear_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_CLEAR, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_delete_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_DELETE, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_set_name_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_SET_NAME, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_set_vorname_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_SET_VORNAME, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_set_anrede_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_SET_ANREDE, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_set_adresse_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_SET_ADRESSE, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_get_name_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_GET_NAME, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_get_vorname_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_GET_VORNAME, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_get_rid_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_GET_RID, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_get_konten_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_GET_KONTEN, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_get_anrede_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_GET_ANREDE, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_get_adresse_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_GET_ADRESSE, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_find_by_key_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_FIND_BY_KEY, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_register_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_REGISTER, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rknd *
knde_unregister_1(rknd *argp, CLIENT *clnt)
{
	static rknd clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, KNDE_UNREGISTER, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_rknd, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

short *
dbms_commit_1(char **argp, CLIENT *clnt)
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DBMS_COMMIT, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_wrapstring, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_short, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

short *
dbms_rollback_1(char **argp, CLIENT *clnt)
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DBMS_ROLLBACK, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_wrapstring, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_short, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

short *
dbms_data_server_changed_1(void *argp, CLIENT *clnt)
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, DBMS_DATA_SERVER_CHANGED, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_void, argp, (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) (xdrproc_t) xdr_short, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
