/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "r_knde.h"
#include <stdio.h>
#include <stdlib.h>/* getenv, exit */
#include <rpc/pmap_clnt.h> /* for pmap_unset */
#include <string.h> /* strcmp */ 
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifdef __STDC__
#define SIG_PF void(*)(int)
#endif

static void
r_knde_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		rknd knde_new_1_arg;
		rknd knde_init_1_arg;
		rknd knde_clear_1_arg;
		rknd knde_delete_1_arg;
		rknd knde_set_name_1_arg;
		rknd knde_set_vorname_1_arg;
		rknd knde_set_anrede_1_arg;
		rknd knde_set_adresse_1_arg;
		rknd knde_get_name_1_arg;
		rknd knde_get_vorname_1_arg;
		rknd knde_get_rid_1_arg;
		rknd knde_get_konten_1_arg;
		rknd knde_get_anrede_1_arg;
		rknd knde_get_adresse_1_arg;
		rknd knde_find_by_key_1_arg;
		rknd knde_register_1_arg;
		rknd knde_unregister_1_arg;
		char *dbms_commit_1_arg;
		char *dbms_rollback_1_arg;
	} argument;
	char *result;
	xdrproc_t xdr_argument, xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case KNDE_NEW:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_new_1_svc;
		break;

	case KNDE_INIT:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_init_1_svc;
		break;

	case KNDE_CLEAR:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_clear_1_svc;
		break;

	case KNDE_DELETE:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_delete_1_svc;
		break;

	case KNDE_SET_NAME:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_set_name_1_svc;
		break;

	case KNDE_SET_VORNAME:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_set_vorname_1_svc;
		break;

	case KNDE_SET_ANREDE:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_set_anrede_1_svc;
		break;

	case KNDE_SET_ADRESSE:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_set_adresse_1_svc;
		break;

	case KNDE_GET_NAME:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_get_name_1_svc;
		break;

	case KNDE_GET_VORNAME:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_get_vorname_1_svc;
		break;

	case KNDE_GET_RID:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_get_rid_1_svc;
		break;

	case KNDE_GET_KONTEN:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_get_konten_1_svc;
		break;

	case KNDE_GET_ANREDE:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_get_anrede_1_svc;
		break;

	case KNDE_GET_ADRESSE:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_get_adresse_1_svc;
		break;

	case KNDE_FIND_BY_KEY:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_find_by_key_1_svc;
		break;

	case KNDE_REGISTER:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_register_1_svc;
		break;

	case KNDE_UNREGISTER:
		xdr_argument = (xdrproc_t) xdr_rknd;
		xdr_result = (xdrproc_t) xdr_rknd;
		local = (char *(*)(char *, struct svc_req *)) knde_unregister_1_svc;
		break;

	case DBMS_COMMIT:
		xdr_argument = (xdrproc_t) xdr_wrapstring;
		xdr_result = (xdrproc_t) xdr_short;
		local = (char *(*)(char *, struct svc_req *)) dbms_commit_1_svc;
		break;

	case DBMS_ROLLBACK:
		xdr_argument = (xdrproc_t) xdr_wrapstring;
		xdr_result = (xdrproc_t) xdr_short;
		local = (char *(*)(char *, struct svc_req *)) dbms_rollback_1_svc;
		break;

	case DBMS_DATA_SERVER_CHANGED:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_short;
		local = (char *(*)(char *, struct svc_req *)) dbms_data_server_changed_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		fprintf(stderr, "unable to free arguments");
		exit(1);
	}
	return;
}

int
rpcgen_main(int argc, char **argv)
{
	register SVCXPRT *transp;

	(void) pmap_unset(R_KNDE, R_KNDE_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf(stderr, "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, R_KNDE, R_KNDE_VERSION, r_knde_1, IPPROTO_UDP)) {
		fprintf(stderr, "unable to register (R_KNDE, R_KNDE_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf(stderr, "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, R_KNDE, R_KNDE_VERSION, r_knde_1, IPPROTO_TCP)) {
		fprintf(stderr, "unable to register (R_KNDE, R_KNDE_VERSION, tcp).");
		exit(1);
	}

	svc_run();
	fprintf(stderr, "svc_run returned");
	exit(1);
	/* NOTREACHED */
}
