/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "r_btab.h"
#include <stdio.h>
#include <stdlib.h>/* getenv, exit */
#include <rpc/pmap_clnt.h> /* for pmap_unset */
#include <string.h> /* strcmp */ 
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifdef __STDC__
#define SIG_PF void(*)(int)
#endif

static void
r_btab_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		rtab btab_new_1_arg;
		rtab btab_init_1_arg;
		rtab btab_clear_1_arg;
		rtab btab_delete_1_arg;
		rtab btab_open_1_arg;
		rtab btab_close_1_arg;
		rtab btab_rewind_1_arg;
		rtab btab_get_next_1_arg;
		rtab btab_get_previous_1_arg;
		rtab btab_get_at_1_arg;
		rtab btab_put_at_1_arg;
		rtab btab_append_1_arg;
		rtab btab_is_empty_1_arg;
		rtab btab_is_not_empty_1_arg;
	} argument;
	char *result;
	xdrproc_t xdr_argument, xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case BTAB_NEW:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_new_1_svc;
		break;

	case BTAB_INIT:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_init_1_svc;
		break;

	case BTAB_CLEAR:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_clear_1_svc;
		break;

	case BTAB_DELETE:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_delete_1_svc;
		break;

	case BTAB_OPEN:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_open_1_svc;
		break;

	case BTAB_CLOSE:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_close_1_svc;
		break;

	case BTAB_REWIND:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_rewind_1_svc;
		break;

	case BTAB_GET_NEXT:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_get_next_1_svc;
		break;

	case BTAB_GET_PREVIOUS:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_get_previous_1_svc;
		break;

	case BTAB_GET_AT:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_get_at_1_svc;
		break;

	case BTAB_PUT_AT:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_put_at_1_svc;
		break;

	case BTAB_APPEND:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_rtab;
		local = (char *(*)(char *, struct svc_req *)) btab_append_1_svc;
		break;

	case BTAB_IS_EMPTY:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_short;
		local = (char *(*)(char *, struct svc_req *)) btab_is_empty_1_svc;
		break;

	case BTAB_IS_NOT_EMPTY:
		xdr_argument = (xdrproc_t) xdr_rtab;
		xdr_result = (xdrproc_t) xdr_short;
		local = (char *(*)(char *, struct svc_req *)) btab_is_not_empty_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		fprintf(stderr, "unable to free arguments");
		exit(1);
	}
	return;
}

int
rpcgen_main(int argc, char **argv)
{
	register SVCXPRT *transp;

	(void) pmap_unset(R_BTAB_KNDE, R_BTAB_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf(stderr, "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, R_BTAB_KNDE, R_BTAB_VERSION, r_btab_1, IPPROTO_UDP)) {
		fprintf(stderr, "unable to register (R_BTAB_KNDE, R_BTAB_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf(stderr, "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, R_BTAB_KNDE, R_BTAB_VERSION, r_btab_1, IPPROTO_TCP)) {
		fprintf(stderr, "unable to register (R_BTAB_KNDE, R_BTAB_VERSION, tcp).");
		exit(1);
	}

	svc_run();
	fprintf(stderr, "svc_run returned");
	exit(1);
	/* NOTREACHED */
}
